### PR TITLE
Fix AddProfile generating malformed XML (Issue #68)

### LINKED ISSUE #68: ConfigureNativeBuild: AddProfile generates malformed XML structure
## Problem

The `ConfigureNativeBuild` recipe uses `AddProfile` to add a native build profile to `pom.xml`, but the generated XML has an invalid structure. The `<properties>` content is rendered as direct children of `<profile>` without the wrapping `<properties>` element, and similarly for `<activation>`.

## Example

**Current output (malformed):**
```xml
<profile>
    <id>native</id>
    <property>
        <name>native</name>
    </property>
    <quarkus.native.enabled>true</quarkus.native.enabled>
    <quarkus.package.jar.enabled>false</quarkus.package.jar.enabled>
</profile>
```

**Expected output:**
```xml
<profile>
    <id>native</id>
    <activation>
        <property>
            <name>native</name>
        </property>
    </activation>
    <properties>
        <quarkus.native.enabled>true</quarkus.native.enabled>
        <quarkus.package.jar.enabled>false</quarkus.package.jar.enabled>
    </properties>
</profile>
```

## Impact

Validated against apollo, cwa-server, mall, jhipster — 20 pom.xml files affected. All generated profiles have invalid XML that Maven won't parse correctly.

## Suggested Fix

This may be an issue with how `AddProfile` renders the `activation` and `properties` parameters. The recipe YAML passes these as XML fragments, but the wrapping elements are missing in the output. Either:
1. The YAML needs to include the wrapping `<activation>` and `<properties>` elements
2. Or `AddProfile` has a bug in how it renders these parameters

## Context

- Found during validation of PR #63 recipes against real-world Spring Boot repositories.

### PR DESCRIPTION
**Pull request by timtebeek**
## Summary
- Added wrapping `<activation>` and `<properties>` elements to `AddProfile` parameters in `spring-native.yml` — the recipe expects these wrappers but they were missing, causing malformed XML output
- Removed `@Disabled` from `CustomizeQuarkusPluginGoalsTest` and added `ConfigureNativeBuildTest`

- Fixes #68

## Test plan
- [x] `CustomizeQuarkusPluginGoalsTest` passes (previously `@Disabled`)
- [x] New `ConfigureNativeBuildTest` verifies correct `<activation>` and `<properties>` structure
- [x] Full test suite passes (one pre-existing unrelated failure in `MigrateDatabaseDriversTest`)

### CODE REVIEW

File: src/test/java/org/openrewrite/quarkus/spring/CustomizeQuarkusPluginGoalsTest.java [hunk 1]
```diff
@@ -15,20 +15,20 @@
...
 
-@Disabled("AddProfile is not idempotent and produces malformed XML")
 class CustomizeQuarkusPluginGoalsTest implements RewriteTest {
 
     @Override
     public void defaults(RecipeSpec spec) {
-        spec.recipeFromResources("org.openrewrite.quarkus.spring.CustomizeQuarkusPluginGoals");
+        spec.recipeFromResources("org.openrewrite.quarkus.spring.CustomizeQuarkusPluginGoals")
+          // AddProfile is not idempotent; it removes and re-adds the profile each cycle
+          .expectedCyclesThatMakeChanges(2);
```
Comment (timtebeek) [inline src/test/java/org/openrewrite/quarkus/spring/CustomizeQuarkusPluginGoalsTest.java]: Upstream fix
- https://github.com/openrewrite/rewrite/pull/7356

**Comment by timtebeek** [comment]
Wasn't yet done publishing the above upstream fix: https://github.com/openrewrite/rewrite/actions/runs/24315242281/job/70991703405
